using System.Text.Json;
using System.Text.Json.Serialization;
using SimScale.Sdk.V1.Models;

namespace SimScale.Sdk.V1.Models.SimulationModels;

public class ConstantFunction : OneOf_DimensionalFunction_HeatFluxValue, OneOf_StressTensor_PressureSigmaXX, OneOf_StressTensor_PressureSigmaYY, OneOf_StressTensor_PressureSigmaZZ, OneOf_StressTensor_PressureSigmaYZ, OneOf_StressTensor_PressureSigmaXZ, OneOf_StressTensor_PressureSigmaXY, OneOf_LinearElasticMarcMaterialBehaviorPoissonsRatio, OneOf_DimensionalFunction_AngleValue, OneOf_DimensionalFunction_LengthValue, OneOf_DimensionalFunction_TemperatureGradientValue, OneOf_RestrictedDimensionalFunction_FrequencyValue, OneOf_RestrictedDimensionalFunction_TimeValue, OneOf_DimensionalFunction_SpecificTurbulenceDissipationRateValue, OneOf_DimensionalFunction_PowerValue, OneOf_DimensionalFunction_KinematicViscosityValue, OneOf_DimensionalFunction_TotalThermalTransmittanceValue, OneOf_IsotropicDirectionalDependencyPoissonsRatio, OneOf_DimensionalFunction_ElectricResistivityValue, OneOf_JohnsonCookElastoPlasticModelPoissonsRatio, OneOf_DimensionalFunction_SpeedValue, OneOf_DimensionalFunction_ElectricConductivityValue, OneOf_DimensionalFunction_ThermalExpansionRateValue, OneOf_DimensionalFunction_DynamicViscosityValue, OneOf_ComponentVectorFunctionX, OneOf_ComponentVectorFunctionY, OneOf_ComponentVectorFunctionZ, OneOf_PrescribedOptionalFunctionValue, OneOf_DimensionalFunction_ElectricPotentialValue, OneOf_DimensionalFunction_TurbulenceKineticEnergyValue, OneOf_DimensionalFunction_AccelerationValue, OneOf_DimensionalFunction_MagneticFluxDensityValue, OneOf_DimensionalFunction_VolumetricFlowRateValue, OneOf_DimensionalFunction_PressureValue, OneOf_DimensionalFunction_TurbulentDissipationValue, OneOf_DimensionalFunction_SpecificEnergyValue, OneOf_IsotropicPlasticHardeningPoissonsRatio, OneOf_DimensionalFunction_TemperatureValue, OneOf_DimensionalFunction_TimeValue, OneOf_DimensionalFunction_SpecificHeatValue, OneOf_DimensionalFunction_RotationSpeedValue, OneOf_DimensionalFunction_ThermalTransmittanceValue, OneOf_DimensionalFunction_DensityValue, OneOf_ElasticityMarcPoissonsRatio, OneOf_OrthotropicDirectionalDependencyPoissonsRatioXY, OneOf_OrthotropicDirectionalDependencyPoissonsRatioYZ, OneOf_OrthotropicDirectionalDependencyPoissonsRatioXZ, OneOf_DimensionalFunction_ElectricFieldStrengthValue, OneOf_DimensionalFunction_ThermalConductivityValue, OneOf_DimensionalFunction_ElectricCurrentValue, OneOf_BilinearElastoPlasticModelPoissonsRatio, OneOf_DimensionalFunction_VolumetricPowerValue, OneOf_DimensionalFunction_MassFlowRateValue, OneOf_DimensionalFunction_DimensionlessValue
{
    /// <summary>Schema name: ConstantFunction</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "CONSTANT";

    [JsonPropertyName("value")]
    public double? Value { get; set; }

}
