using System.Text.Json;
using System.Text.Json.Serialization;
using SimScale.Sdk.V1.Models;

namespace SimScale.Sdk.V1.Models.SimulationModels;

public class ExpressionFunction : OneOf_DimensionalFunction_ElectricConductivityValue, OneOf_DimensionalFunction_ElectricPotentialValue, OneOf_RestrictedDimensionalFunction_FrequencyValue, OneOf_DimensionalFunction_DimensionlessValue, OneOf_DimensionalFunction_KinematicViscosityValue, OneOf_DimensionalFunction_ElectricCurrentValue, OneOf_DimensionalFunction_ThermalExpansionRateValue, OneOf_RestrictedDimensionalFunction_TimeValue, OneOf_DimensionalFunction_AccelerationValue, OneOf_DimensionalFunction_ThermalTransmittanceValue, OneOf_BilinearElastoPlasticModelPoissonsRatio, OneOf_DimensionalFunction_SpecificTurbulenceDissipationRateValue, OneOf_DimensionalFunction_AngleValue, OneOf_DimensionalFunction_ThermalConductivityValue, OneOf_DimensionalFunction_SpeedValue, OneOf_ComponentVectorFunctionX, OneOf_ComponentVectorFunctionY, OneOf_ComponentVectorFunctionZ, OneOf_DimensionalFunction_TurbulenceKineticEnergyValue, OneOf_DimensionalFunction_PowerValue, OneOf_DimensionalFunction_TemperatureValue, OneOf_IsotropicPlasticHardeningPoissonsRatio, OneOf_JohnsonCookElastoPlasticModelPoissonsRatio, OneOf_IsotropicDirectionalDependencyPoissonsRatio, OneOf_LinearElasticMarcMaterialBehaviorPoissonsRatio, OneOf_DimensionalFunction_VolumetricPowerValue, OneOf_DimensionalFunction_SpecificEnergyValue, OneOf_DimensionalFunction_DynamicViscosityValue, OneOf_DimensionalFunction_ElectricFieldStrengthValue, OneOf_DimensionalFunction_TemperatureGradientValue, OneOf_DimensionalFunction_TurbulentDissipationValue, OneOf_DimensionalFunction_TimeValue, OneOf_DimensionalFunction_DensityValue, OneOf_DimensionalFunction_LengthValue, OneOf_DimensionalFunction_MagneticFluxDensityValue, OneOf_ElasticityMarcPoissonsRatio, OneOf_DimensionalFunction_HeatFluxValue, OneOf_PrescribedOptionalFunctionValue, OneOf_DimensionalFunction_RotationSpeedValue, OneOf_DimensionalFunction_ElectricResistivityValue, OneOf_DimensionalFunction_VolumetricFlowRateValue, OneOf_DimensionalFunction_TotalThermalTransmittanceValue, OneOf_DimensionalFunction_MassFlowRateValue, OneOf_DimensionalFunction_SpecificHeatValue, OneOf_DimensionalFunction_PressureValue, OneOf_StressTensor_PressureSigmaXX, OneOf_StressTensor_PressureSigmaYY, OneOf_StressTensor_PressureSigmaZZ, OneOf_StressTensor_PressureSigmaYZ, OneOf_StressTensor_PressureSigmaXZ, OneOf_StressTensor_PressureSigmaXY, OneOf_OrthotropicDirectionalDependencyPoissonsRatioXY, OneOf_OrthotropicDirectionalDependencyPoissonsRatioYZ, OneOf_OrthotropicDirectionalDependencyPoissonsRatioXZ
{
    /// <summary>Schema name: ExpressionFunction</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "EXPRESSION";

    [JsonPropertyName("expression")]
    public string? Expression { get; set; }

    [JsonPropertyName("availableVariables")]
    public List<FunctionParameter>? AvailableVariables { get; set; }

}
